services:
  back:
    build: ./tmpbackend
    ports:
      - '8000:8000'
  frontend:
    build: ./frontend
    ports:
      - '443:443'
    volumes:
      - front:/var/www/html

volumes:
  front:
    driver: local
    driver_opts:
      type: 'none'
      o:    'bind'
      device: ./frontend/src # change for local machine
