services:
  frontend:
    build: ./frontend
    ports:

      - '8443:8443'
    volumes:
      - ./frontend/src:/var/www/html
      - ./backend/media:/media
    networks:
      - transc_network
    depends_on:
      - backend

  db:
    image: postgres:16.4-bullseye
    container_name: transc_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ".env"
    expose:
      - 5432
    networks:
      - transc_network

  backend:
    build: ./backend
    container_name: transc_backend
    volumes:
      - ./backend:/code
    expose:
      - "8000"
    depends_on:
      - db
    env_file: ".env"
    networks:
      - transc_network

volumes:
  postgres_data:
    name: postgres_data

networks:
  transc_network:
    name: transc_network
    driver: bridge
